<a href="https://colab.research.google.com/github/Kavya-158/Kavya-158/blob/main/Tableau.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Connect the google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Read CSV as pandas data frame
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/CompAndViz/CityScore.csv')
df

,metric_name,score_calculated_ts,target,metric_logic,day_score,day_numerator,day_denominator,week_score,week_numerator,week_denominator,month_score,month_numerator,month_denominator,quarter_score,quarter_numerator,quarter_denominator,latest_score_flag
0,BFD INCIDENTS,2024-10-02 18:58:15.95516,NaN,historical_average / current_average,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN,0
1,BFD INCIDENTS,2024-09-30 19:26:00.049142,NaN,historical_average / current_average,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,232.598214,NaN,NaN,226.166667,NaN,0
2,LIBRARY USERS,2024-09-28 18:57:25.240849,NaN,current_average / historical_average,NaN,NaN,9075.689655,NaN,NaN,9075.689655,NaN,NaN,9147.316239,NaN,NaN,8851.279006,0
3,BFD INCIDENTS,2024-10-03 18:58:29.889671,NaN,historical_average / current_average,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN,1
4,BFD INCIDENTS,2024-10-01 18:58:14.357528,NaN,historical_average / current_average,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57058,311 CONSTITUENT EXPERIENCE SURVEYS,2018-03-13 14:36:51,4.0,sum(numerator_value)/sum(denominator_value)/ta...,NaN,NaN,NaN,NaN,NaN,NaN,1.075000,43.000000,10.000000,1.000000,156.000000,39.000000,0
57059,GRAFFITI ON-TIME %,2021-10-24 07:25:51.221647,0.8,sum(numerator_value)/sum(denominator_value)/ta...,NaN,NaN,NaN,0.395833,19.000000,60.000000,0.768634,198.000000,322.000000,0.713429,476.000000,834.000000,0
57060,SIGN INSTALLATION ON-TIME %,2021-11-02 07:26:52.805246,0.8,sum(numerator_value)/sum(denominator_value)/ta...,0.795455,7.000000,11.000000,0.301724,7.000000,29.000000,0.411932,29.000000,88.000000,0.486707,227.000000,583.000000,0
57061,PARKS MAINTENANCE ON-TIME %,2021-11-02 07:30:08.607259,0.8,sum(numerator_value)/sum(denominator_value)/ta...,1.250000,8.000000,8.000000,0.937500,24.000000,32.000000,0.923252,243.000000,329.000000,0.962942,1003.000000,1302.000000,0
57062,TREE MAINTENANCE ON-TIME %,2021-11-02 07:30:24.382527,0.8,sum(numerator_value)/sum(denominator_value)/ta...,0.937500,3.000000,4.000000,1.234940,82.000000,83.000000,1.196581,224.000000,234.000000,1.158425,759.000000,819.000000,0

In [ ]:
#Check the number of rows and columns
df.shape

(57063, 17)

In [ ]:
#Gives the data types of the columns
df.dtypes

metric_name             object
score_calculated_ts     object
target                 float64
metric_logic            object
day_score              float64
day_numerator          float64
day_denominator        float64
week_score             float64
week_numerator         float64
week_denominator       float64
month_score            float64
month_numerator        float64
month_denominator      float64
quarter_score          float64
quarter_numerator      float64
quarter_denominator    float64
latest_score_flag        int64
dtype: object

In [ ]:
# Describe the data
df.describe(include = 'all')

,metric_name,score_calculated_ts,target,metric_logic,day_score,day_numerator,day_denominator,week_score,week_numerator,week_denominator,month_score,month_numerator,month_denominator,quarter_score,quarter_numerator,quarter_denominator,latest_score_flag
count,57063,57063,42307.000000,57063,36933.000000,43660.000000,37536.000000,51747.000000,54066.000000,52222.000000,55048.000000,5.550800e+04,5.536500e+04,55495.000000,5.571100e+04,5.621300e+04,57063.000000
unique,23,48355,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,POTHOLE ON-TIME %,2018-07-21 22:51:28,NaN,sum(numerator_value)/sum(denominator_value)/ta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2547,22,NaN,37559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,1.489631,NaN,1.169156,1314.125579,1740.594563,1.079060,6600.175339,7896.260170,1.058817,2.773545e+04,3.076280e+04,1.032654,8.278862e+04,9.030089e+04,0.000386
std,NaN,NaN,1.473233,NaN,2.003045,6164.490633,8138.758980,1.151567,35050.411744,43210.073751,0.833721,1.448352e+05,1.596356e+05,0.392962,4.128280e+05,4.516240e+05,0.019632
min,NaN,NaN,0.800000,NaN,0.000000,0.000000,1.000000,0.000000,0.000000,0.142857,0.000000,0.000000e+00,3.225806e-02,0.000000,0.000000e+00,2.173913e-02,0.000000
25%,NaN,NaN,0.800000,NaN,0.898481,3.000000,6.000000,0.875000,18.000000,26.857143,0.879630,6.300000e+01,4.238710e+01,0.883413,2.151200e+02,7.100000e+01,0.000000
50%,NaN,NaN,0.800000,NaN,1.071429,13.000000,20.000000,1.019645,59.000000,72.000000,1.016082,2.237426e+02,2.580000e+02,1.014419,6.580000e+02,7.570000e+02,0.000000
75%,NaN,NaN,0.950000,NaN,1.250000,74.000000,155.000000,1.213235,239.190476,302.000000,1.194449,1.084000e+03,1.259000e+03,1.177852,3.369000e+03,3.798000e+03,0.000000
max,NaN,NaN,6.000000,NaN,204.238095,191635.000000,221903.000000,57.428571,288106.000000,878774.000000,66.028226,1.134223e+06,1.231902e+06,54.207493,2.952483e+06,3.246289e+06,1.000000

In [ ]:
df['metric_name'].value_counts()

metric_name
POTHOLE ON-TIME %                     2547
311 CALL CENTER PERFORMANCE           2547
PARKS MAINTENANCE ON-TIME %           2547
MISSED TRASH ON-TIME %                2547
SIGNAL REPAIR ON-TIME %               2547
311 CONSTITUENT EXPERIENCE SURVEYS    2547
SIGN INSTALLATION ON-TIME %           2547
STREETLIGHT ON-TIME %                 2547
CODE ENFORCEMENT TRASH COLLECTION     2546
TREE MAINTENANCE ON-TIME %            2546
CODE ENFORCEMENT ON-TIME %            2546
CITY SERVICES SATISFACTION SURVEYS    2546
BFD RESPONSE TIME                     2546
LIBRARY USERS                         2545
BPS ATTENDANCE                        2545
BFD INCIDENTS                         2443
PART 1 CRIMES                         2442
HOMICIDES (TREND)                     2442
STABBINGS (TREND)                     2442
SHOOTINGS (TREND)                     2442
GRAFFITI ON-TIME %                    2430
EMS RESPONSE TIME                     2203
ON-TIME PERMIT REVIEWS                2023
Name: count, dtype: int64

In [ ]:
#Show the top 10 rows
df.head(10)

,metric_name,score_calculated_ts,target,metric_logic,day_score,day_numerator,day_denominator,week_score,week_numerator,week_denominator,month_score,month_numerator,month_denominator,quarter_score,quarter_numerator,quarter_denominator,latest_score_flag
0,BFD INCIDENTS,2024-10-02 18:58:15.95516,NaN,historical_average / current_average,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN,0
1,BFD INCIDENTS,2024-09-30 19:26:00.049142,NaN,historical_average / current_average,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,232.598214,NaN,NaN,226.166667,NaN,0
2,LIBRARY USERS,2024-09-28 18:57:25.240849,NaN,current_average / historical_average,NaN,NaN,9075.689655,NaN,NaN,9075.689655,NaN,NaN,9147.316239,NaN,NaN,8851.279006,0
3,BFD INCIDENTS,2024-10-03 18:58:29.889671,NaN,historical_average / current_average,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN,1
4,BFD INCIDENTS,2024-10-01 18:58:14.357528,NaN,historical_average / current_average,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN,0
5,BFD INCIDENTS,2024-09-26 19:32:17.460489,NaN,historical_average / current_average,NaN,231.761905,NaN,NaN,231.761905,NaN,NaN,232.598214,NaN,NaN,226.166667,NaN,0
6,LIBRARY USERS,2024-09-24 19:15:04.697895,NaN,current_average / historical_average,NaN,NaN,9075.689655,NaN,NaN,9075.689655,NaN,NaN,9147.316239,NaN,NaN,8851.279006,0
7,LIBRARY USERS,2024-09-27 18:58:23.537848,NaN,current_average / historical_average,NaN,NaN,9075.689655,NaN,NaN,9075.689655,NaN,NaN,9147.316239,NaN,NaN,8851.279006,0
8,LIBRARY USERS,2024-09-21 19:11:52.277142,NaN,current_average / historical_average,NaN,NaN,8969.785714,NaN,NaN,8969.785714,NaN,NaN,9147.316239,NaN,NaN,8851.279006,0
9,LIBRARY USERS,2024-09-25 19:16:40.217604,NaN,current_average / historical_average,NaN,NaN,9075.689655,NaN,NaN,9075.689655,NaN,NaN,9147.316239,NaN,NaN,8851.279006,0

In [ ]:
#Drop the rows which you feel are not important
df = df.drop(columns=['metric_logic','latest_score_flag'])

In [ ]:
df

,metric_name,score_calculated_ts,target,day_score,day_numerator,day_denominator,week_score,week_numerator,week_denominator,month_score,month_numerator,month_denominator,quarter_score,quarter_numerator,quarter_denominator
0,BFD INCIDENTS,2024-10-02 18:58:15.95516,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN
1,BFD INCIDENTS,2024-09-30 19:26:00.049142,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,232.598214,NaN,NaN,226.166667,NaN
2,LIBRARY USERS,2024-09-28 18:57:25.240849,NaN,NaN,NaN,9075.689655,NaN,NaN,9075.689655,NaN,NaN,9147.316239,NaN,NaN,8851.279006
3,BFD INCIDENTS,2024-10-03 18:58:29.889671,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN
4,BFD INCIDENTS,2024-10-01 18:58:14.357528,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57058,311 CONSTITUENT EXPERIENCE SURVEYS,2018-03-13 14:36:51,4.0,NaN,NaN,NaN,NaN,NaN,NaN,1.075000,43.000000,10.000000,1.000000,156.000000,39.000000
57059,GRAFFITI ON-TIME %,2021-10-24 07:25:51.221647,0.8,NaN,NaN,NaN,0.395833,19.000000,60.000000,0.768634,198.000000,322.000000,0.713429,476.000000,834.000000
57060,SIGN INSTALLATION ON-TIME %,2021-11-02 07:26:52.805246,0.8,0.795455,7.000000,11.000000,0.301724,7.000000,29.000000,0.411932,29.000000,88.000000,0.486707,227.000000,583.000000
57061,PARKS MAINTENANCE ON-TIME %,2021-11-02 07:30:08.607259,0.8,1.250000,8.000000,8.000000,0.937500,24.000000,32.000000,0.923252,243.000000,329.000000,0.962942,1003.000000,1302.000000
57062,TREE MAINTENANCE ON-TIME %,2021-11-02 07:30:24.382527,0.8,0.937500,3.000000,4.000000,1.234940,82.000000,83.000000,1.196581,224.000000,234.000000,1.158425,759.000000,819.000000

In [ ]:
#Change the data type of the timestamp value to datetime format
df['score_calculated_ts'] = pd.to_datetime(df['score_calculated_ts'],format='mixed')
df

,metric_name,score_calculated_ts,target,day_score,day_numerator,day_denominator,week_score,week_numerator,week_denominator,month_score,month_numerator,month_denominator,quarter_score,quarter_numerator,quarter_denominator
0,BFD INCIDENTS,2024-10-02 18:58:15.955160,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN
1,BFD INCIDENTS,2024-09-30 19:26:00.049142,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,232.598214,NaN,NaN,226.166667,NaN
2,LIBRARY USERS,2024-09-28 18:57:25.240849,NaN,NaN,NaN,9075.689655,NaN,NaN,9075.689655,NaN,NaN,9147.316239,NaN,NaN,8851.279006
3,BFD INCIDENTS,2024-10-03 18:58:29.889671,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN
4,BFD INCIDENTS,2024-10-01 18:58:14.357528,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57058,311 CONSTITUENT EXPERIENCE SURVEYS,2018-03-13 14:36:51.000000,4.0,NaN,NaN,NaN,NaN,NaN,NaN,1.075000,43.000000,10.000000,1.000000,156.000000,39.000000
57059,GRAFFITI ON-TIME %,2021-10-24 07:25:51.221647,0.8,NaN,NaN,NaN,0.395833,19.000000,60.000000,0.768634,198.000000,322.000000,0.713429,476.000000,834.000000
57060,SIGN INSTALLATION ON-TIME %,2021-11-02 07:26:52.805246,0.8,0.795455,7.000000,11.000000,0.301724,7.000000,29.000000,0.411932,29.000000,88.000000,0.486707,227.000000,583.000000
57061,PARKS MAINTENANCE ON-TIME %,2021-11-02 07:30:08.607259,0.8,1.250000,8.000000,8.000000,0.937500,24.000000,32.000000,0.923252,243.000000,329.000000,0.962942,1003.000000,1302.000000
57062,TREE MAINTENANCE ON-TIME %,2021-11-02 07:30:24.382527,0.8,0.937500,3.000000,4.000000,1.234940,82.000000,83.000000,1.196581,224.000000,234.000000,1.158425,759.000000,819.000000

In [ ]:
#Consider the date value for the timestamp column
df['score_calculated_ts'] = df['score_calculated_ts'].dt.date
df

,metric_name,score_calculated_ts,target,day_score,day_numerator,day_denominator,week_score,week_numerator,week_denominator,month_score,month_numerator,month_denominator,quarter_score,quarter_numerator,quarter_denominator
0,BFD INCIDENTS,2024-10-02,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN
1,BFD INCIDENTS,2024-09-30,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,232.598214,NaN,NaN,226.166667,NaN
2,LIBRARY USERS,2024-09-28,NaN,NaN,NaN,9075.689655,NaN,NaN,9075.689655,NaN,NaN,9147.316239,NaN,NaN,8851.279006
3,BFD INCIDENTS,2024-10-03,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN
4,BFD INCIDENTS,2024-10-01,NaN,NaN,237.238095,NaN,NaN,237.238095,NaN,NaN,238.252747,NaN,NaN,230.558480,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57058,311 CONSTITUENT EXPERIENCE SURVEYS,2018-03-13,4.0,NaN,NaN,NaN,NaN,NaN,NaN,1.075000,43.000000,10.000000,1.000000,156.000000,39.000000
57059,GRAFFITI ON-TIME %,2021-10-24,0.8,NaN,NaN,NaN,0.395833,19.000000,60.000000,0.768634,198.000000,322.000000,0.713429,476.000000,834.000000
57060,SIGN INSTALLATION ON-TIME %,2021-11-02,0.8,0.795455,7.000000,11.000000,0.301724,7.000000,29.000000,0.411932,29.000000,88.000000,0.486707,227.000000,583.000000
57061,PARKS MAINTENANCE ON-TIME %,2021-11-02,0.8,1.250000,8.000000,8.000000,0.937500,24.000000,32.000000,0.923252,243.000000,329.000000,0.962942,1003.000000,1302.000000
57062,TREE MAINTENANCE ON-TIME %,2021-11-02,0.8,0.937500,3.000000,4.000000,1.234940,82.000000,83.000000,1.196581,224.000000,234.000000,1.158425,759.000000,819.000000

In [ ]:
df['metric_name'].value_counts()

metric_name
POTHOLE ON-TIME %                     2547
311 CALL CENTER PERFORMANCE           2547
PARKS MAINTENANCE ON-TIME %           2547
MISSED TRASH ON-TIME %                2547
SIGNAL REPAIR ON-TIME %               2547
311 CONSTITUENT EXPERIENCE SURVEYS    2547
SIGN INSTALLATION ON-TIME %           2547
STREETLIGHT ON-TIME %                 2547
CODE ENFORCEMENT TRASH COLLECTION     2546
TREE MAINTENANCE ON-TIME %            2546
CODE ENFORCEMENT ON-TIME %            2546
CITY SERVICES SATISFACTION SURVEYS    2546
BFD RESPONSE TIME                     2546
LIBRARY USERS                         2545
BPS ATTENDANCE                        2545
BFD INCIDENTS                         2443
PART 1 CRIMES                         2442
HOMICIDES (TREND)                     2442
STABBINGS (TREND)                     2442
SHOOTINGS (TREND)                     2442
GRAFFITI ON-TIME %                    2430
EMS RESPONSE TIME                     2203
ON-TIME PERMIT REVIEWS                2023
Name: count, dtype: int64

In [ ]:
#Check for null values
df.isna()

,metric_name,score_calculated_ts,target,day_score,day_numerator,day_denominator,week_score,week_numerator,week_denominator,month_score,month_numerator,month_denominator,quarter_score,quarter_numerator,quarter_denominator
0,False,False,True,True,False,True,True,False,True,True,False,True,True,False,True
1,False,False,True,True,False,True,True,False,True,True,False,True,True,False,True
2,False,False,True,True,True,False,True,True,False,True,True,False,True,True,False
3,False,False,True,True,False,True,True,False,True,True,False,True,True,False,True
4,False,False,True,True,False,True,True,False,True,True,False,True,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57058,False,False,False,True,True,True,True,True,True,False,False,False,False,False,False
57059,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
57060,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
57061,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
57062,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df['month_score'].isna().value_counts()

month_score
False    55048
True      2015
Name: count, dtype: int64

Check the percentage of null values present in the columns to decide as to keep or delete the data. The day score data has about 30% of null values. Therefore we can drop the rows with null values and continue with the rest of the data.

In [ ]:
df_cleaned = df.dropna()
df_cleaned

,metric_name,score_calculated_ts,target,day_score,day_numerator,day_denominator,week_score,week_numerator,week_denominator,month_score,month_numerator,month_denominator,quarter_score,quarter_numerator,quarter_denominator
12,311 CALL CENTER PERFORMANCE,2024-09-19,0.95,0.916646,910.0,1045.000000,0.976188,5887.0,6348.0,0.967239,25769.0,28044.0,0.957930,75055.0,82475.000000
22,311 CALL CENTER PERFORMANCE,2024-09-10,0.95,0.953570,1184.0,1307.000000,0.943597,5504.0,6140.0,0.967239,25769.0,28044.0,0.957930,75055.0,82475.000000
23,311 CALL CENTER PERFORMANCE,2024-09-02,0.95,0.911085,457.0,528.000000,0.972542,6278.0,6795.0,0.967239,25769.0,28044.0,0.957930,75055.0,82475.000000
25,311 CALL CENTER PERFORMANCE,2024-10-03,0.95,0.994586,891.0,943.000000,0.981832,5242.0,5620.0,0.959098,23410.0,25693.0,0.955116,73596.0,81110.000000
26,311 CALL CENTER PERFORMANCE,2024-10-01,0.95,0.989571,1020.0,1085.000000,0.981832,5242.0,5620.0,0.959098,23410.0,25693.0,0.955116,73596.0,81110.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57038,GRAFFITI ON-TIME %,2019-11-13,0.80,0.000000,0.0,7.000000,0.000000,0.0,36.0,0.867159,188.0,271.0,0.939286,789.0,1050.000000
57050,EMS RESPONSE TIME,2020-09-20,6.00,0.970350,6.0,6.183333,0.967742,6.0,6.2,1.000000,6.0,6.0,1.037464,6.0,5.783333
57060,SIGN INSTALLATION ON-TIME %,2021-11-02,0.80,0.795455,7.0,11.000000,0.301724,7.0,29.0,0.411932,29.0,88.0,0.486707,227.0,583.000000
57061,PARKS MAINTENANCE ON-TIME %,2021-11-02,0.80,1.250000,8.0,8.000000,0.937500,24.0,32.0,0.923252,243.0,329.0,0.962942,1003.0,1302.000000
57062,TREE MAINTENANCE ON-TIME %,2021-11-02,0.80,0.937500,3.0,4.000000,1.234940,82.0,83.0,1.196581,224.0,234.0,1.158425,759.0,819.000000

In [ ]:
df_cleaned['metric_name'].value_counts()

metric_name
CODE ENFORCEMENT ON-TIME %            2194
CODE ENFORCEMENT TRASH COLLECTION     2148
SIGNAL REPAIR ON-TIME %               2115
311 CALL CENTER PERFORMANCE           2110
PARKS MAINTENANCE ON-TIME %           2090
MISSED TRASH ON-TIME %                2068
CITY SERVICES SATISFACTION SURVEYS    2065
BFD RESPONSE TIME                     2061
STREETLIGHT ON-TIME %                 1932
EMS RESPONSE TIME                     1912
POTHOLE ON-TIME %                     1774
TREE MAINTENANCE ON-TIME %            1516
SIGN INSTALLATION ON-TIME %           1383
GRAFFITI ON-TIME %                     953
ON-TIME PERMIT REVIEWS                 903
311 CONSTITUENT EXPERIENCE SURVEYS     887
BPS ATTENDANCE                         840
Name: count, dtype: int64

In [ ]:
# Create a mapping dictionary for sector names
sector_mapping = {
    'BFD RESPONSE TIME': 'Public safety and Health',
    'EMS RESPONSE TIME': 'Public safety and Health',
    'SIGNAL REPAIR ON-TIME %': 'Transportation Management',
    'STREETLIGHT ON-TIME %': 'Transportation Management',
    'POTHOLE ON-TIME %': 'Transportation Management',
    'SIGN INSTALLATION ON-TIME %': 'Transportation Management',
    'BPS ATTENDANCE': 'Basic city services',
    'CODE ENFORCEMENT ON-TIME %': 'Basic city services',
    'CODE ENFORCEMENT TRASH COLLECTION': 'Basic city services',
    '311 CALL CENTER PERFORMANCE': 'Basic city services',
    'PARKS MAINTENANCE ON-TIME %': 'Basic city services',
    'MISSED TRASH ON-TIME %': 'Basic city services',
    'TREE MAINTENANCE ON-TIME %': 'Basic city services',
    'CITY SERVICES SATISFACTION SURVEYS': 'Constituent satisfaction',
    'GRAFFITI ON-TIME %': 'Basic city services',
    'ON-TIME PERMIT REVIEWS': 'Constituent satisfaction',
    '311 CONSTITUENT EXPERIENCE SURVEYS': 'Constituent satisfaction'
}

# Map the sector names to a new column in the DataFrame
df_cleaned['sector_name'] = df_cleaned['metric_name'].map(sector_mapping)

# Display the updated DataFrame
print(df_cleaned)

                       metric_name score_calculated_ts  target  day_score  \
12     311 CALL CENTER PERFORMANCE          2024-09-19    0.95   0.916646
22     311 CALL CENTER PERFORMANCE          2024-09-10    0.95   0.953570
23     311 CALL CENTER PERFORMANCE          2024-09-02    0.95   0.911085
25     311 CALL CENTER PERFORMANCE          2024-10-03    0.95   0.994586
26     311 CALL CENTER PERFORMANCE          2024-10-01    0.95   0.989571
...                            ...                 ...     ...        ...
57038           GRAFFITI ON-TIME %          2019-11-13    0.80   0.000000
57050            EMS RESPONSE TIME          2020-09-20    6.00   0.970350
57060  SIGN INSTALLATION ON-TIME %          2021-11-02    0.80   0.795455
57061  PARKS MAINTENANCE ON-TIME %          2021-11-02    0.80   1.250000
57062   TREE MAINTENANCE ON-TIME %          2021-11-02    0.80   0.937500

       day_numerator  day_denominator  week_score  week_numerator  \
12             910.0      1045.000000    0.976188          5887.0
22            1184.0      1307.000000    0.943597          5504.0
23             457.0       528.000000    0.972542          6278.0
25             891.0       943.000000    0.981832          5242.0
26            1020.0      1085.000000    0.981832          5242.0
...              ...              ...         ...             ...
57038            0.0         7.000000    0.000000             0.0
57050            6.0         6.183333    0.967742             6.0
57060            7.0        11.000000    0.301724             7.0
57061            8.0         8.000000    0.937500            24.0
57062            3.0         4.000000    1.234940            82.0

       week_denominator  month_score  month_numerator  month_denominator  \
12               6348.0     0.967239          25769.0            28044.0
22               6140.0     0.967239          25769.0            28044.0
23               6795.0     0.967239          25769.0            28044.0
25               5620.0     0.959098          23410.0            25693.0
26               5620.0     0.959098          23410.0            25693.0
...                 ...          ...              ...                ...
57038              36.0     0.867159            188.0              271.0
57050               6.2     1.000000              6.0                6.0
57060              29.0     0.411932             29.0               88.0
57061              32.0     0.923252            243.0              329.0
57062              83.0     1.196581            224.0              234.0

       quarter_score  quarter_numerator  quarter_denominator  \
12          0.957930            75055.0         82475.000000
22          0.957930            75055.0         82475.000000
23          0.957930            75055.0         82475.000000
25          0.955116            73596.0         81110.000000
26          0.955116            73596.0         81110.000000
...              ...                ...                  ...
57038       0.939286              789.0          1050.000000
57050       1.037464                6.0             5.783333
57060       0.486707              227.0           583.000000
57061       0.962942             1003.0          1302.000000
57062       1.158425              759.0           819.000000

                     sector_name
12           Basic city services
22           Basic city services
23           Basic city services
25           Basic city services
26           Basic city services
...                          ...
57038        Basic city services
57050   Public safety and Health
57060  Transportation Management
57061        Basic city services
57062        Basic city services

[28951 rows x 16 columns]

<ipython-input-12-97fc87075660>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['sector_name'] = df_cleaned['metric_name'].map(sector_mapping)

In [ ]:
df_cleaned

,metric_name,score_calculated_ts,target,day_score,day_numerator,day_denominator,week_score,week_numerator,week_denominator,month_score,month_numerator,month_denominator,quarter_score,quarter_numerator,quarter_denominator,sector_name
12,311 CALL CENTER PERFORMANCE,2024-09-19,0.95,0.916646,910.0,1045.000000,0.976188,5887.0,6348.0,0.967239,25769.0,28044.0,0.957930,75055.0,82475.000000,Basic city services
22,311 CALL CENTER PERFORMANCE,2024-09-10,0.95,0.953570,1184.0,1307.000000,0.943597,5504.0,6140.0,0.967239,25769.0,28044.0,0.957930,75055.0,82475.000000,Basic city services
23,311 CALL CENTER PERFORMANCE,2024-09-02,0.95,0.911085,457.0,528.000000,0.972542,6278.0,6795.0,0.967239,25769.0,28044.0,0.957930,75055.0,82475.000000,Basic city services
25,311 CALL CENTER PERFORMANCE,2024-10-03,0.95,0.994586,891.0,943.000000,0.981832,5242.0,5620.0,0.959098,23410.0,25693.0,0.955116,73596.0,81110.000000,Basic city services
26,311 CALL CENTER PERFORMANCE,2024-10-01,0.95,0.989571,1020.0,1085.000000,0.981832,5242.0,5620.0,0.959098,23410.0,25693.0,0.955116,73596.0,81110.000000,Basic city services
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57038,GRAFFITI ON-TIME %,2019-11-13,0.80,0.000000,0.0,7.000000,0.000000,0.0,36.0,0.867159,188.0,271.0,0.939286,789.0,1050.000000,Basic city services
57050,EMS RESPONSE TIME,2020-09-20,6.00,0.970350,6.0,6.183333,0.967742,6.0,6.2,1.000000,6.0,6.0,1.037464,6.0,5.783333,Public safety and Health
57060,SIGN INSTALLATION ON-TIME %,2021-11-02,0.80,0.795455,7.0,11.000000,0.301724,7.0,29.0,0.411932,29.0,88.0,0.486707,227.0,583.000000,Transportation Management
57061,PARKS MAINTENANCE ON-TIME %,2021-11-02,0.80,1.250000,8.0,8.000000,0.937500,24.0,32.0,0.923252,243.0,329.0,0.962942,1003.0,1302.000000,Basic city services
57062,TREE MAINTENANCE ON-TIME %,2021-11-02,0.80,0.937500,3.0,4.000000,1.234940,82.0,83.0,1.196581,224.0,234.0,1.158425,759.0,819.000000,Basic city services

After the null values are removed we can convert the score values of metrics into binary values for easy understanding as we know that a value above 1 indicates a good day and a value less that 1 is an unsatisfactory day.

In [ ]:
columns_to_modify = ['day_score', 'week_score', 'month_score','quarter_score']  # list of column names
df_cleaned[columns_to_modify] = df_cleaned[columns_to_modify].apply(lambda x: np.where(x < 1, 0, 1))

<ipython-input-14-5e03fd480c2e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[columns_to_modify] = df_cleaned[columns_to_modify].apply(lambda x: np.where(x < 1, 0, 1))

In [ ]:
df_cleaned

,metric_name,score_calculated_ts,target,day_score,day_numerator,day_denominator,week_score,week_numerator,week_denominator,month_score,month_numerator,month_denominator,quarter_score,quarter_numerator,quarter_denominator,sector_name
12,311 CALL CENTER PERFORMANCE,2024-09-19,0.95,0,910.0,1045.000000,0,5887.0,6348.0,0,25769.0,28044.0,0,75055.0,82475.000000,Basic city services
22,311 CALL CENTER PERFORMANCE,2024-09-10,0.95,0,1184.0,1307.000000,0,5504.0,6140.0,0,25769.0,28044.0,0,75055.0,82475.000000,Basic city services
23,311 CALL CENTER PERFORMANCE,2024-09-02,0.95,0,457.0,528.000000,0,6278.0,6795.0,0,25769.0,28044.0,0,75055.0,82475.000000,Basic city services
25,311 CALL CENTER PERFORMANCE,2024-10-03,0.95,0,891.0,943.000000,0,5242.0,5620.0,0,23410.0,25693.0,0,73596.0,81110.000000,Basic city services
26,311 CALL CENTER PERFORMANCE,2024-10-01,0.95,0,1020.0,1085.000000,0,5242.0,5620.0,0,23410.0,25693.0,0,73596.0,81110.000000,Basic city services
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57038,GRAFFITI ON-TIME %,2019-11-13,0.80,0,0.0,7.000000,0,0.0,36.0,0,188.0,271.0,0,789.0,1050.000000,Basic city services
57050,EMS RESPONSE TIME,2020-09-20,6.00,0,6.0,6.183333,0,6.0,6.2,1,6.0,6.0,1,6.0,5.783333,Public safety and Health
57060,SIGN INSTALLATION ON-TIME %,2021-11-02,0.80,0,7.0,11.000000,0,7.0,29.0,0,29.0,88.0,0,227.0,583.000000,Transportation Management
57061,PARKS MAINTENANCE ON-TIME %,2021-11-02,0.80,1,8.0,8.000000,0,24.0,32.0,0,243.0,329.0,0,1003.0,1302.000000,Basic city services
57062,TREE MAINTENANCE ON-TIME %,2021-11-02,0.80,0,3.0,4.000000,1,82.0,83.0,1,224.0,234.0,1,759.0,819.000000,Basic city services

In [ ]:
df_cleaned['metric_name'].value_counts()

metric_name
CODE ENFORCEMENT ON-TIME %            2194
CODE ENFORCEMENT TRASH COLLECTION     2148
SIGNAL REPAIR ON-TIME %               2115
311 CALL CENTER PERFORMANCE           2110
PARKS MAINTENANCE ON-TIME %           2090
MISSED TRASH ON-TIME %                2068
CITY SERVICES SATISFACTION SURVEYS    2065
BFD RESPONSE TIME                     2061
STREETLIGHT ON-TIME %                 1932
EMS RESPONSE TIME                     1912
POTHOLE ON-TIME %                     1774
TREE MAINTENANCE ON-TIME %            1516
SIGN INSTALLATION ON-TIME %           1383
GRAFFITI ON-TIME %                     953
ON-TIME PERMIT REVIEWS                 903
311 CONSTITUENT EXPERIENCE SURVEYS     887
BPS ATTENDANCE                         840
Name: count, dtype: int64

In [ ]:
#Convert the dataframe to a csv file for further visualizations
df_cleaned.to_csv('assignment1.csv')